### PR TITLE
Grove_SI114X.CPP

### PR DESCRIPTION
**Pull request by airdissy**
Hello,
So I'm quite new to Wio link for a week now and I'm working hard to make my sunlight and dust sensor working.
So here is just a copy of the arduino grove driver of sunlight sensor with the right header I supposed for Wio_link. I'm not expert in that but tried to do the right way.
I wished to test with my own server but still in troubles to launch it. (I have separate topics here : )
Thanks,
Peter

### CODE REVIEW

**Comment by awong1900** [comment]
Thank you Peter.

**Comment by airdissy** [comment]
Perfect, Should I see it within a day in the official wio-link application?
I've seen the two file in the directory but not in a specific folder grove_SI114X, is-it ok?
Thanks !

**Comment by awong1900** [comment]
@airdissy I check your pull, i think it's not work. You need use suli2 to port the driver. Refer to others i2c driver. I will revert your pull, and make a branch you can do it.

**Comment by awong1900** [comment]
@airdissy the branch is https://github.com/Seeed-Studio/Grove_Drivers_for_Wio/tree/feature/grove_SI114X
you can fork it, fix it, then pull request. If ok , I will merger to master.
Let me know any question.

**Pull request merged**
